```{r} library(tidyverse) library(tidyselect) library(tibble) library(lubridate) library(sf) library(tigris) library(lubridate) library(tidygeocoder) library(gt) library(gtsummary) # nice count visualizations library(forcats) # a specific data wrangling issue library(readxl) library(wordcloud) library(rstatix) ``` THIS IS STILL A MAJOR WORK IN PROGRESS. I JUST HAVE THE RAW FORMAT HERE. > I need to add Canadian trips to my dataset and exclude them in the United States portion (or maybe incorporate? I don't know at the moment) # The United States ```{r} # Regions defined by the U.S. census bureau northeast <- c("Massachusetts", "New Hampshire", "Vermont", "Connecticut", "Maine", "Rhode Island", "New York", "New Jersey", "Pennsylvania") midwest <- c("Illinois", "Indiana", "Michigan", "Ohio", "Wisconsin", "Iowa", "Kansas", "Minnesota", "Missouri", "Nebraska", "North Dakota", "South Dakota") south <- c("Delaware", "DC", "Florida", "Georgia", "Maryland", "North Carolina", "South Carolina", "Virginia", "West Virginia", "Alabama", "Kentucky", "Mississippi", "Tennessee", "Arkansas", "Louisiana", "Oklahoma", "Texas") west <- c("Arizona", "Colorado", "Idaho", "Montana", "Nevada", "New Mexico", "Utah", "Wyoming", "Alaska", "California", "Hawaii", "Oregon", "Washington") ``` ```{r, output = FALSE} # data that I type in manually daniel_travel_map <- readxl::read_xlsx("trip_data.xlsx") |> # I can also add coordinate information here... maybe play around with that? mutate(start_date = as_date(start_date), end_date=as_date(end_date)) |> mutate(region = case_when( state %in% northeast ~ "Northeast", state %in% midwest ~ "Midwest", state %in% south ~ "South", state %in% west ~ "West" )) |> mutate(travel_length = as.integer(end_date - start_date) + 1) |> mutate(travel_year = year(start_date)) |> drop_na() #any NA is removed # these are places I don't want included us_territories <- c("VI", "GU", "MP", "AS") # US states shapefile us <- states(cb = TRUE, resolution="5m") |> filter(!(STUSPS %in% us_territories)) |> shift_geometry() #for alaska and hawaii (and PR) ``` These visualizations do not take into account smaller trips within the state I live in (e.g. travelling from Allston to Boston doesn't count, but something like Haverhill to Fall River counts). These are just ones I thought were memorable. Thus, I don't count just passing through a state. I also don't count states I have lived in; that will probably be a separate visualization. > I still have yet to add states in which I lived there (perhaps it will be added to the "visit" indicator somehow) ```{r} # Counts capital_counts <- daniel_travel_map |> filter(capital_indicator == "Yes") |> distinct(state) |> as_vector() visit_counts <- daniel_travel_map |> count(state, name="visits") |> mutate(capital_indicator = ifelse(state %in% capital_counts, 1, 0)) # Also gather information from "lived" dataset ``` ```{r} # Join counts to map travel_count_map <- us |> left_join( visit_counts, by=c("NAME" = "state") ) |> mutate( visits=ifelse(is.na(visits), 0, visits), visit_indicator=ifelse(visits == 0, 0, 1), capital_indicator=ifelse(is.na(capital_indicator), 0, capital_indicator) ) ``` > Currently unconvinced of the dotted and solid lines ```{r, fig.width=18, fig.height=12} # Plot ggplot(data = travel_count_map) + geom_sf(aes(fill = factor(visit_indicator), linetype=factor(capital_indicator)), linewidth=1) + scale_fill_manual( values=c("0" = "white", "1" = "lightblue"), labels=c("No", "Yes"), name="Visited State") + scale_linetype_manual( values=c("0" = "dotted", "1" = "solid"), labels=c("No", "Yes"), name="Visited Capital" ) + theme_bw() + theme( axis.text = element_blank(), panel.grid = element_blank(), legend.position = "bottom") + labs( title="Have I been to the state?" ) ``` 2. Timeline on unique states I have been to (manually add states I lived in like California), and on the X axis, show the state name. > Still a couple of fixes I want here since it's not 100% accurate but it's fine ```{r} # first, count unique states from the earliest I've been there first_travel <- daniel_travel_map |> group_by(state) |> filter(start_date == min(start_date)) |> # somehow this worked lol rename(first_visit_date = start_date) |> ungroup(state) first_travel <- first_travel |> mutate(states_visited_order = nrow(first_travel) - row_number() + 1) #again, stupid fix but it works # now we can plot it ggplot(data = first_travel, aes(x = first_visit_date, y = states_visited_order)) + geom_step() + geom_text(aes(label = state, color = region), nudge_x = -225, size = 3) + theme_bw() + labs(x = "Date of First Travel (incomplete)", y = "Number of States", title = "States visited for the first time", color = "Region") ``` 3. Small multiples visualization of states I have visited each year + lived in (lived in part will be hard to implement + if I didn't travel at all, it won't appear + if I didn't travel to that state, the state won't be there...) ```{r} # first, loop through the minimum and maximum years of my dataset year_min <- min(daniel_travel_map$travel_year) year_max <- max(daniel_travel_map$travel_year) # I'm going to vectorize this in a minute travel_duration_map <- purrr::map_dfr(year_min:year_max, \(yr) { daniel_travel_map |> filter(travel_year == yr) |> right_join(us, by=c("state" = "NAME")) |> mutate( travel_year = yr, travel_length = coalesce(travel_length, 0) ) }) # some quick selection to make data process cleaner travel_duration_map <- travel_duration_map |> dplyr::select(state, travel_length, travel_year, STUSPS, geometry) |> mutate(lived_indicator = ifelse(state == "Massachusetts", 1, 0)) |> #this is temporary st_as_sf() ``` > I have yet to add my lived data. Maps won't look too different ```{r} # get range of years daniel_lived_data <- readxl::read_xlsx("lived_data.xlsx") # create a new row for each year and each state I have lived in (another loop from 2008 to 2026 and beyond) ``` ```{r, fig.width=18, fig.height=12} # the plot! ggplot(data = travel_duration_map) + geom_sf(aes(fill = travel_length, color = factor(lived_indicator))) + scale_fill_viridis_c(name = "Trips") + scale_fill_gradient(low = "white", high = "blue") + scale_color_manual( values = c("0" = "grey40", "1" = "orange"), labels = c("No", "Yes") ) + facet_wrap(~ travel_year) + theme_bw() + theme(axis.text = element_blank(), panel.grid = element_blank(), legend.position = "bottom") + labs(title = "Duration of stay in each state per year", fill = "Length of Travel (Days)", color = "Lived here?") ``` 3.5. Approximately when did I visit each state? ```{r} state_dates <- data.frame( state = c( "Delaware","Pennsylvania","New Jersey","Georgia","Connecticut","Massachusetts", "Maryland","South Carolina","New Hampshire","Virginia","New York","North Carolina", "Rhode Island","Vermont","Kentucky","Tennessee","Ohio","Louisiana","Indiana", "Mississippi","Illinois","Alabama","Maine","Missouri","Arkansas","Michigan", "Florida","Texas","Iowa","Wisconsin","California","Minnesota","Oregon", "Kansas","West Virginia","Nevada","Nebraska","Colorado","North Dakota", "South Dakota","Montana","Washington","Idaho","Wyoming","Utah","Oklahoma", "New Mexico","Arizona","Alaska","Hawaii","DC" ), date_joined = as.Date(c( "1787-12-07","1787-12-12","1787-12-18","1788-01-02","1788-01-09","1788-02-06", "1788-04-28","1788-05-23","1788-06-21","1788-06-25","1788-07-26","1789-11-21", "1790-05-29","1791-03-04","1792-06-01","1796-06-01","1803-03-01","1812-04-30", "1816-12-11","1817-12-10","1818-12-03","1819-12-14","1820-03-15","1821-08-10", "1836-06-15","1837-01-26","1845-03-03","1845-12-29","1846-12-28","1848-05-29", "1850-09-09","1858-05-11","1859-02-14","1861-01-29","1863-06-20","1864-10-31", "1867-03-01","1876-08-01","1889-11-02","1889-11-02","1889-11-08","1889-11-11", "1890-07-03","1890-07-10","1896-01-04","1907-11-16","1912-01-06","1912-02-14", "1959-01-03","1959-08-21","1790-07-16" # DC last )) ) daniel_travel_map_ordered <- daniel_travel_map |> mutate(state = factor(state, levels=state_dates$state[order(state_dates$date_joined, decreasing=TRUE)])) ggplot(data = daniel_travel_map_ordered, aes(x = start_date, y=state, color=region)) + geom_point() + theme_bw() + labs(x = "Year", y="State", color="Region", title="Every Visit ordered by when the state joined the union") ``` 4. Word cloud of my travel descriptions (this is currently a placeholder) ```{r, results=FALSE} daniel_travel_map |> dplyr::select(desc) dfm <- c("pear", "apple", "orange") d <- freq_table(dfm)[,c(1,3)] colnames(d) <- c("word", "freq") wordcloud (words=d$word, freq=d$freq, min.freq=150, max.words=150, random.order=FALSE, rot.per=0.3, colors=brewer.pal(8, "Dark2")) ``` 5. Descriptive statistics: how many redeyes, how many business vs leisure trips, distribution of days I stayed (faceted by something), average length of trip by days, number of day trips, average distance of trips (MAYBE) etc.> Also this is where I will put the sheer number of times I have travelled to each state ```{r} ggplot(data = daniel_travel_map, aes(x = travel_length)) + geom_histogram() + theme_bw() ``` 7. Lines of travel (How have I travelled between each state?): May not work if I don't have proper coordinates. Maybe I can do it based on thickness? 8. A county map? Includes places I've just passed by (do this manually): something approximate.